services:
  app:
    container_name: app
    build:
      context: ./app
      args:
        - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run dev
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    networks:
      - overwatch

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - ${CLICKHOUSE_HTTP_PORT}:8123  # HTTP interface
      - ${CLICKHOUSE_NATIVE_PORT}:9000  # Native interface
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./clickhouse/data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    networks:
      - overwatch

networks:
  overwatch:
    driver: bridge

volumes:
  node_modules:
    driver: local