services:
  app:
    build:
      context: ./app
      args:
        - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run dev
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    networks:
      - overwatch

networks:
  overwatch:
    driver: bridge

volumes:
  node_modules:
    driver: local