apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: overwatch
      port: ${CLICKHOUSE_PORT}
      host: ${CLICKHOUSE_HOST}
      username: ${CLICKHOUSE_USER}
      tlsSkipVerify: false
      logs:
        defaultDatabase: overwatch
        defaultTable: app_logs
        otelEnabled: true
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}